language: node_js
node_js:
  - "9.11.1"
services:
  - mongodb
script:
  - node src/index.js &
  - npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
